version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: twitter-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aspire
      MYSQL_DATABASE: twitter
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: